pipeline:
  build:
    image: alpine
    commands:
      - apk --no-cache add python3 ca-certificates gcc musl-dev python3-dev
      - pip3 install .[testing]
      - pytest

  slack:
    image: plugins/slack
    channel: bots
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
      event: push

  email:
    image: drillster/drone-email
    from: ci@secondarymetabolites.org
    host: mail.secondarymetabolites.org
    username: antismash
    secrets: [ email_password ]
    when:
      status: [ success, failure ]
      event: push
